# Generated by Django 3.2.8 on 2021-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hid', models.IntegerField()),
                ('Sid', models.IntegerField()),
                ('bdate', models.CharField(max_length=20)),
                ('status', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
