# Generated by Django 3.2.8 on 2021-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sfn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='sln',
            field=models.CharField(default='', max_length=50),
        ),
    ]
