# Generated by Django 3.2.8 on 2021-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0002_auto_20211205_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('attendance', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
