# Generated by Django 3.2.8 on 2021-12-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0005_remove_attendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
